apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: demo
data:
  redis.conf: |
    dbfilename "dump.rdb"
    protected-mode no
    dir /var/lib/redis
    save 3600 1
    save 300 10
    save 60 100
    appendonly yes
    appendfilename "appendonly.aof"    